---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jamesdbloom/docker-java8-maven
    tag: "latest"

inputs:
- name: git-assets

outputs:
- name: application-jar
  path: git-assets/boot-sample/concourse-demo.jar

run:
  path: git-assets/boot-sample/ci/tasks/package.sh
