---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/deploy-worker
    tag: "latest"

inputs:
- name: git-assets

run:
  path: git-assets/boot-sample/mvnw
  args:
  - test
