---
resources:
- name: resource-manifest
  type: git
  source:
    uri: https://github.com/azwickey-pivotal/concourse-pipeline-samples

- name: resource-bosh-release
  type: s3
  source:
    bucket: downloads-abz
    regexp: GemFire-dev.(.*).tgz

- name: resource-bosh-stemcell
  type: bosh-io-stemcell
  source:
    name: {{bosh-stemcell-name}}

- name: resource-gf-bosh-deployment
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    client_id: {{bosh-username}}
    client_secret: {{bosh-password}}
    ca_cert: {{ca-cert}}
    deployment: p-gemfire-350429c97c17f1d02bf6 # from the manifest.yml in resource-manifest
    ignore_ssl: true

jobs:
- name: job-deploy
  public: true
  serial: true
  plan:
  - aggregate:
    - get: resource-bosh-stemcell
    - get: resource-bosh-release
    - get: resource-manifest
  - put: resource-gf-bosh-deployment
    params:
      manifest: resource-manifest/bosh-2.0/cf-gemfire.yml
      releases:
        - resource-bosh-release/GemFire-dev.4.tgz
      stemcells:
        - resource-bosh-stemcell/*.tgz
