resources:
- name: git-assets
  type: git
  source:
    branch: master
    uri: https://github.com/azwickey-pivotal/concourse-pipeline-samples

jobs:
- name: test-complile
  public: true
  plan:
  - get: git-assets
    trigger: true
  - task: mvn-test
    file: boot-sample/ci/tasks/mvn-test.yml
